CREATE TABLE DEPARTMENT(
    DEPT_ID CHAR(2),
    DEPT_TITLE VARCHAR(35),
    LOCATION_ID CHAR(2)
);
COMMENT ON COLUMN DEPARTMENT.DEPT_ID is '부서코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_TITLE is '부서명';
COMMENT ON COLUMN DEPARTMENT.LOCATION_ID is '지역코드';
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_TITLE, LOCATION_ID)
VALUES ('D1','인사관리부','L1'); 
INSERT INTO DEPARTMENT VALUES ('D2','회계관리부','L1');
INSERT INTO DEPARTMENT VALUES ('D3','마케팅부','L1');
INSERT INTO DEPARTMENT VALUES ('D4','국내영업부','L1');
INSERT INTO DEPARTMENT VALUES ('D5','해외영업1부','L2');
INSERT INTO DEPARTMENT VALUES ('D6','해외영업2부','L3');
INSERT INTO DEPARTMENT VALUES ('D7','해외영업3부','L4');
INSERT INTO DEPARTMENT VALUES ('D8','기술지원부','L5');
INSERT INTO DEPARTMENT VALUES ('D9','총무부','L1');

SELECT *
FROM DEPARTMENT;

CREATE TABLE EMPLOYEE(
EMP_ID VARCHAR2(3),
EMP_NAME VARCHAR(20),
EMP_NO CHAR(14),
EMAIL VARCHAR2(25),
DEPT_CODE CHAR(2),
JOB_CODE CHAR(2),
SAL_LEVEL CHAR(2),
SALARY NUMBER,
BONUS NUMBER,
MANAGER_ID VARCHAR2(3),
HIRE_DATE DATE,
ENT_DATE DATE,
ENT_YN CHAR(1)
);

COMMENT ON COLUMN EMPLOYEE.EMP_ID is '사원번호';
COMMENT ON COLUMN EMPLOYEE.EMP_NAME is '직원명';
COMMENT ON COLUMN EMPLOYEE.EMP_NO is '주민등록번호';
COMMENT ON COLUMN EMPLOYEE.EMAIL is '이메일';
COMMENT ON COLUMN EMPLOYEE.PHONE is '전화번호';
COMMENT ON COLUMN EMPLOYEE.DEPT_CODE is '부서코드';
COMMENT ON COLUMN EMPLOYEE.JOB_CODE is '직급코드';
COMMENT ON COLUMN EMPLOYEE.SAL_LEVEL is '급여등급';
COMMENT ON COLUMN EMPLOYEE.SALARY is '급여';
COMMENT ON COLUMN EMPLOYEE.BONUS is '보너스율';
COMMENT ON COLUMN EMPLOYEE.MANAGER_ID is '관리자사번';
COMMENT ON COLUMN EMPLOYEE.HIRE_DATE is '입사일';
COMMENT ON COLUMN EMPLOYEE.ENT_DATE is '퇴사일';
COMMENT ON COLUMN EMPLOYEE.ENT_YN is '재직여부';


CREATE TABLE JOB(
JOB_CODE CHAR(2),
JOB_NAME VARCHAR(35)
);

INSERT INTO JOB (JOB_CODE, JOB_NAME)
VALUES ('J1', '대표');
INSERT INTO JOB VALUES ('J2', '부사장');
INSERT INTO JOB VALUES ('j3', '부장');
INSERT INTO JOB VALUES ('j4', '차장');
INSERT INTO JOB VALUES ('J5', '과장');
INSERT INTO JOB VALUES ('J6', '대리');
INSERT INTO JOB VALUES ('J7', '사원');

COMMENT ON COLUMN JOB.JOB_CODE is '직급코드';
COMMENT ON COLUMN JOB.JOB_NAME is '직급명';

SELECT *
FROM JOB;

CREATE TABLE LOCATION(
LOCAL_CODE CHAR(2),
NAIONAL_CODE VARCHAR2(35),
LOCAL_NAME VARCHAR(40)
);

INSERT INTO LOCATION VALUES ('L1', 'KO', 'ASIA1');
INSERT INTO LOCATION VALUES ('L2', 'JP', 'ASIA2');
INSERT INTO LOCATION VALUES ('L3', 'CH', 'ASIA3');
INSERT INTO LOCATION VALUES ('L4', 'US', 'AMERICA');
INSERT INTO LOCATION VALUES ('L5', 'RU', 'EU');

COMMENT ON COLUMN LOCATION.LOCAL_CODE is '지역코드';
COMMENT ON COLUMN LOCATION.NATIONAL_CODE is '국가코드';
COMMENT ON COLUMN LOCATION.LOCAL_NAME is '지역명';

SELECT *
FROM LOCATION;

CREATE TABLE NATIONAL(
NATIONAL_CODE CHAR(2),
NATIONAL_NAME VARCHAR2(35)
);

INSERT INTO NATIONAL VALUES ('KO', '한국');
INSERT INTO NATIONAL VALUES ('JP', '일본');
INSERT INTO NATIONAL VALUES ('CH', '중국');
INSERT INTO NATIONAL VALUES ('US', '미국');
INSERT INTO NATIONAL VALUES ('RU', '러시아');

COMMENT ON COLUMN NATIONAL.NATIONAL_CODE is '국가코드';
COMMENT ON COLUMN NATIONAL.NATIONAL_NAME is '국가명';

SELECT *
FROM NATIONAL;

CREATE TABLE SAL_GRADE (
SAL_LEVEL CHAR(2),
MIN_SAL NUMBER,
MAX_SAL NUMBER
);

INSERT INTO SAL_GRADE VALUES ('S1', 6000000, 10000000);
INSERT INTO SAL_GRADE VALUES ('S2', 5000000, 5999999);
INSERT INTO SAL_GRADE VALUES ('S3', 4000000, 4999999);
INSERT INTO SAL_GRADE VALUES ('S4', 3000000, 3999999);
INSERT INTO SAL_GRADE VALUES ('S5', 2000000, 2999999);
INSERT INTO SAL_GRADE VALUES ('S6', 1000000, 1999999);

COMMENT ON COLUMN SAL_GRADE.SAL_LEVEL is '급여등급';
COMMENT ON COLUMN SAL_GRADE.MIN_SAL is '최소급여';
COMMENT ON COLUMN SAL_GRADE.MAX_SAL is '최대급여';

SELECT *
FROM SAL_GRADE;








