-- ORA-01031: insufficient privileges 권한부여 후 재접속 해야함 
--Table STUDENT_TBL이(가) 생성되었습니다.
CREATE TABLE STUDENT_TBL(
    STUDENT_NAME VARCHAR(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR2(100)
);
-- 수정 -> 삭제 + 생성 
-- 테이블 삭제
-- 00942. 00000 -  "table or view does not exist"
DROP TABLE STUDENT_TBL;
-- Table STUDENT_TBL이(가) 삭제되었습니다.

-- TABLE에 데이터를 넣는 방법! -> 회원가입
INSERT INTO STUDENT_TBL(STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS)
VALUES('일용자', 22, 1, '서울');
-- 1 행 이(가) 삽입되었습니다.

-- 컬럼명 생략가능 
INSERT INTO STUDENT_TBL VALUES ('이용자', 33, 2, '서울시 종로구');
INSERT INTO STUDENT_TBL VALUES ('김용자', 33, 1, '서울');
INSERT INTO STUDENT_TBL VALUES ('최용자', 44, 2, '부산');
INSERT INTO STUDENT_TBL VALUES ('신용자', 55, 3, '충청도');

-- 정보 변경 
UPDATE STUDENT_TBL
SET STUDENT_AGE = 99
WHERE STUDENT_GRADE = 2;

DELETE FROM STUDENT_TBL WHERE STUDENT_GRADE = 2;

INSERT INTO STUDENT_TBL
VALUES (' ', 55, 4, NULL);

-- 전체 데이터 삭제 -> 회원탈퇴
DELETE FROM STUDENT_TBL; 
-- 5개 행 이(가) 삭제되었습니다.

-- Table DATATYPE_TEL이(가) 생성되었습니다.
CREATE TABLE DATATYPE_TBL (
    MOONJJA CHAR(10),
    -- 알파벳은 10글자, 한글은 3글자
    MOONJJAYUL VARCHAR2(100), 
    -- 알파벳은 100글자, 한글은 33글자
    SOOJJA NUMBER,
    NALJJA DATE,
    NALJJA2 TIMESTAMP
);
DROP TABLE DATATYPE_TEL;

DESC DATATYPE_TBL;
INSERT INTO DATATYPE_TBL
VALUES('문자','문자열', 22, SYSDATE, SYSTIMESTAMP);
SELECT MOONJJA, MOONJJAYUL, SOOJJA, NALJJA, NALJJA2
FROM DATATYPE_TBL;
INSERT INTO DATATYPE_TBL
VALUES('문자2', '문자열2', 33, SYSDATE, SYSTIMESTAMP);

UPDATE DATATYPE_TBL
SET MOONJJAYUL = '오라클'
WHERE SOOJJA = 33;
-- 1 행 이(가) 업데이트되었습니다.

DELETE FROM DATATYPE_TBL
WHERE SOOJJA = 22;
-- 1 행 이(가) 삭제되었습니다.

-- 데이터 조회
-- FROM -> WHERE -> SELECT
SELECT STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS
FROM STUDENT_TBL
WHERE STUDENT_GRADE = 1;
